[project]
name = "multilang-stacktrace"
version = "0.1.0"
description = "Stack straces from 30 programming languages for 4 faulty programs"
readme = "README.md"
authors = [{name = "Quinten Cabo"}]
requires-python = ">=3.10"
dependencies = [
    "pyarrow>=21.0.0",
]
